### PR TITLE
Update CookieAuthenticate.php

### PR DESCRIPTION
**Pull request by mbglytch**
Fixing _matchingData not selected #1

### CODE REVIEW

**Comment by nojimage** [comment]
Thanks, pull request.

It seems broken when query not set `selelct` params.

Check the query `->select($this->getTokensTable())` using `Query::clause('select')` mehtod:

eg:
```
if (!empty($query->clause('select'))) {
    $query->select($this->getTokensTable());
}
```

**Comment by mbglytch** [comment]
You are right. I do not know how to add a commit to an existing pull request. Maybe i can let you fix this.

**Comment by nojimage** [comment]
OK, I'll change it. 👍

**Comment by nojimage** [comment]
This PR branch is missed, I created new PR #3 .

**Pull request closed without merging**
